wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1667723117.092227
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.4
      8:
      - 5
amp:
  desc: null
  value: true
amp_level:
  desc: null
  value: O2
batch_size:
  desc: null
  value: 512
datasets_path:
  desc: null
  value: ../../input
epochs:
  desc: null
  value: 1
feature_dim:
  desc: null
  value: 128
k:
  desc: null
  value: 200
results_path:
  desc: null
  value: results
resume:
  desc: null
  value: false
resume_path:
  desc: null
  value: results/128_0.5_200_512_10.pth
seed:
  desc: null
  value: 1
start_epoch:
  desc: null
  value: 1
temperature:
  desc: null
  value: 0.5
use_checkpoint:
  desc: null
  value: false
wandb:
  desc: null
  value: run
